##################################################
# Reprodução
##################################################

# Fecha o MPV quando a reprodução termina
idle=no

# Salva a posição do vídeo ao fechar
save-position-on-quit=yes
resume-playback=yes


##################################################
# Áudio
##################################################

# Preferência de idioma
alang=pt-BR

# Volume
volume=70
volume-max=200


##################################################
# Legendas
##################################################

# Prioriza legendas em português
slang=pt-BR,pt-BR,pt,por,ptBR,pob

sub-color='#FFFF00'
sub-border-color='#000000'
sub-border-size=2
sub-ass-override=no


##################################################
# Interface (OSD / OSC)
##################################################

# Esconde os controles na tela
osc=no

# Barra da OSD
osd-bar-h=3
osd-color='#FFFF00'


##################################################
# Janela
##################################################

# Sem borda
border=no

# Limita o tamanho máximo da janela
autofit-larger=98%x98%

# Comportamento padrão
ontop=no

# Entrar/sair do mini player PiP
Ctrl+p script-binding pip/toggle-pip

# Decodificar GPU 

hwdec=auto-safe

